#!/usr/bin/env bash
# native-smoke.sh - native executable smoke-test helper.
#
# Why this exists:
# - Keeps native smoke-test assertions reusable outside Taskfile.yml.
# - Proves plain `./target/codegeist --version` prints only the build version
#   while application logs go into `target/smoke-test/codegeist.log`.
#
# Inputs:
# - `target/codegeist`, built by `task native` or the native Maven profile.
# - `target/classes/META-INF/build-info.properties`, generated by Maven build-info.
#
# Side effects:
# - Removes and recreates `target/smoke-test` before the smoke run.
# - Executes `./target/codegeist --version` from the CLI module root.
#
# Related files:
# - Taskfile.yml
# - src/main/resources/logback.xml

set -euo pipefail

run-native-smoke-tests() {
  local script_dir
  local cli_dir
  local smoke_dir
  local expected
  local actual

  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  cli_dir="$(cd -- "$script_dir/.." && pwd)"
  smoke_dir="$cli_dir/target/smoke-test"

  cd "$cli_dir"

  expected="$(while IFS='=' read -r key value; do
    [ "$key" = 'build.version' ] && { printf '%s' "$value"; break; }
  done < target/classes/META-INF/build-info.properties)"

  rm -rf "$smoke_dir"
  mkdir -p "$smoke_dir"

  actual="$(LOG_FILE="$smoke_dir/codegeist.log" ./target/codegeist --version 2>&1)"

  if [ "$actual" != "$expected" ]; then
    printf 'Expected version %s, got %s\n' "$expected" "$actual"
    return 1
  fi

  test -s "$smoke_dir/codegeist.log"
}
