version: '3'

tasks:
  test:
    desc: Run the Codegeist test suite
    cmds:
      - mvn --batch-mode --no-transfer-progress test

  build:
    desc: Build the executable Codegeist application jar
    cmds:
      - mvn --batch-mode --no-transfer-progress -DskipTests clean package

  native:
    desc: Build the GraalVM native executable
    cmds:
      - mvn --batch-mode --no-transfer-progress -DskipTests -Pnative clean native:compile

  run:
    desc: Build and run the Codegeist application
    deps:
      - build
    cmds:
      - java -jar target/codegeist.jar
