# setup.ps1 - provision the Windows QEMU smoke VM.
#
# Why this exists:
# - Runs once inside the Windows VM from the local answer ISO generated by
#   qemu-windows-vm.sh.
# - Enables OpenSSH, installs the pinned build tools needed by windows-smoke.ps1,
#   and keeps the VM reachable for non-interactive local smoke runs.
#
# Inputs:
# - setup-config.ps1 on the CGSETUP answer ISO.
# - authorized_keys on the same ISO.
#
# Related files:
# - scripts/tests/qemu-windows-vm.sh
# - scripts/tests/windows-smoke.ps1

$ErrorActionPreference = "Stop"

function Find-SetupRoot {
    $volume = Get-Volume | Where-Object { $_.FileSystemLabel -eq "CGSETUP" } | Select-Object -First 1
    if (-not $volume) {
        throw "CGSETUP answer ISO was not found"
    }

    return "$($volume.DriveLetter):"
}

function Add-ToMachinePath {
    param([string]$PathEntry)

    $current = [Environment]::GetEnvironmentVariable("Path", "Machine")
    $entries = $current -split ";" | Where-Object { $_ }

    if ($entries -notcontains $PathEntry) {
        [Environment]::SetEnvironmentVariable("Path", ($entries + $PathEntry -join ";"), "Machine")
        $env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [Environment]::GetEnvironmentVariable("Path", "User")
    }
}

function Download-File {
    param(
        [string]$Url,
        [string]$OutFile
    )

    Write-Host "Downloading $Url"
    Invoke-WebRequest -Uri $Url -OutFile $OutFile -UseBasicParsing
}

function Install-OpenSsh {
    $installed = Get-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
    if ($installed.State -ne "Installed") {
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
    }

    Start-Service sshd
    Set-Service -Name sshd -StartupType Automatic

    if (-not (Get-NetFirewallRule -Name sshd -ErrorAction SilentlyContinue)) {
        New-NetFirewallRule -Name sshd `
            -DisplayName "OpenSSH Server" `
            -Enabled True `
            -Direction Inbound `
            -Protocol TCP `
            -Action Allow `
            -LocalPort 22 | Out-Null
    }
}

function Install-AuthorizedKey {
    param([string]$SetupRoot)

    $authorizedKeySource = Join-Path $SetupRoot "authorized_keys"
    $authorizedKeyTarget = "C:\ProgramData\ssh\administrators_authorized_keys"

    if (-not (Test-Path -LiteralPath $authorizedKeySource)) {
        throw "authorized_keys not found on answer ISO"
    }

    New-Item -ItemType Directory -Force "C:\ProgramData\ssh" | Out-Null
    Copy-Item -LiteralPath $authorizedKeySource -Destination $authorizedKeyTarget -Force
    & icacls $authorizedKeyTarget /inheritance:r /grant "Administrators:F" /grant "SYSTEM:F" | Out-Null
}

function Install-GraalVm {
    param([string]$Url)

    if (Get-Command native-image -ErrorAction SilentlyContinue) {
        return
    }

    $toolsDir = "C:\tools"
    $archive = Join-Path $toolsDir "graalvm.zip"
    New-Item -ItemType Directory -Force $toolsDir | Out-Null
    Download-File $Url $archive
    Expand-Archive -LiteralPath $archive -DestinationPath $toolsDir -Force

    $graalHome = Get-ChildItem -LiteralPath $toolsDir -Directory |
        Where-Object { $_.Name -like "graalvm*" } |
        Select-Object -First 1

    if (-not $graalHome) {
        throw "GraalVM archive did not expand to a graalvm directory"
    }

    [Environment]::SetEnvironmentVariable("JAVA_HOME", $graalHome.FullName, "Machine")
    [Environment]::SetEnvironmentVariable("GRAALVM_HOME", $graalHome.FullName, "Machine")
    Add-ToMachinePath (Join-Path $graalHome.FullName "bin")
}

function Install-Maven {
    param([string]$Url)

    if (Get-Command mvn -ErrorAction SilentlyContinue) {
        return
    }

    $toolsDir = "C:\tools"
    $archive = Join-Path $toolsDir "maven.zip"
    New-Item -ItemType Directory -Force $toolsDir | Out-Null
    Download-File $Url $archive
    Expand-Archive -LiteralPath $archive -DestinationPath $toolsDir -Force

    $mavenHome = Get-ChildItem -LiteralPath $toolsDir -Directory |
        Where-Object { $_.Name -like "apache-maven-*" } |
        Select-Object -First 1

    if (-not $mavenHome) {
        throw "Maven archive did not expand to an apache-maven directory"
    }

    [Environment]::SetEnvironmentVariable("MAVEN_HOME", $mavenHome.FullName, "Machine")
    Add-ToMachinePath (Join-Path $mavenHome.FullName "bin")
}

function Install-VsBuildTools {
    param([string]$Url)

    if (Get-Command cl.exe -ErrorAction SilentlyContinue) {
        return
    }

    $toolsDir = "C:\tools"
    $installer = Join-Path $toolsDir "vs_BuildTools.exe"
    New-Item -ItemType Directory -Force $toolsDir | Out-Null
    Download-File $Url $installer

    $args = @(
        "--quiet",
        "--wait",
        "--norestart",
        "--nocache",
        "--installPath", "C:\BuildTools",
        "--add", "Microsoft.VisualStudio.Workload.VCTools",
        "--includeRecommended"
    )

    $process = Start-Process -FilePath $installer -ArgumentList $args -PassThru -Wait
    if ($process.ExitCode -ne 0 -and $process.ExitCode -ne 3010) {
        throw "Visual Studio Build Tools installer failed with exit code $($process.ExitCode)"
    }
}

$setupRoot = Find-SetupRoot
. (Join-Path $setupRoot "setup-config.ps1")

Write-Host "Provisioning Codegeist Windows smoke VM"

Install-OpenSsh
Install-AuthorizedKey $setupRoot
Install-GraalVm $CodegeistGraalVmUrl
Install-Maven $CodegeistMavenUrl
Install-VsBuildTools $CodegeistVsBuildToolsUrl

New-Item -ItemType Directory -Force $CodegeistRepoDir | Out-Null
Set-Content -LiteralPath $CodegeistReadyFile -Value "ready" -Encoding ASCII
Write-Host "Codegeist Windows smoke VM provisioning complete"
